version: ~> 1.0
os: linux
dist: xenial   # required for Python >= 3.7
language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "nightly"
jobs:
  include:
      - python: "3.6"
      - python: "3.7"
      - python: "3.8"
      - python: "nightly"
      - name: "mypy"
        install: pip install mypy
        script: mypy primes.py binary_search.py --strict
      - name: "pylint"
        install: pip install pylint
        script: pylint primes.py binary_search.py
      - name: "Unit Tests"
        script: python test.py
      - name: "Coverage"
        install: pip install coverage
        script: coverage run --include=primes.py,test.py,binary_search.py test.py && coverage report -m --fail-under=100 --rcfile=coveragerc
      - name: "Speed Test All"
        script: python speed_test.py --all
      - name: "Speed Test 6 Fermat Numbers"
        script: python speed_test.py --fermat 6
