version: ~> 1.0
os: linux
dist: xenial   # required for Python >= 3.7
language: python
jobs:
  include:
      - &mypy
        name: "mypy"
        install: pip install mypy
        script: mypy primes.py binary_search.py --strict
      - <<: *mypy
        python: "nightly"
      - &pylint
        name: "pylint"
        install: pip install pylint
        script: pylint primes.py binary_search.py
      - <<: *pylint
        python: "nightly"
      - &unit-tests
        name: "Unit Tests"
        script: python test.py
      - <<: *unit-tests
        python: "3.6"
      - <<: *unit-tests
        python: "3.7"
      - <<: *unit-tests
        python: "3.8"
      - <<: *unit-tests
        python: "nightly"
      - &coverage
        name: "Coverage"
        install: pip install coverage
        script: coverage run --include=primes.py,test.py,binary_search.py test.py && coverage report -m --fail-under=100 --rcfile=coveragerc
      - <<: *coverage
        python: "nightly"
      - &speed-test-all
        name: "Speed Test All"
        python: "3.6"
        script: python speed_test.py --all
      - <<: *speed-test-all
        python: "3.6"
      - <<: *speed-test-all
        python: "3.7"
      - <<: *speed-test-all
        python: "3.8"
      - <<: *speed-test-all
        python: "nightly"
      - &speed-test-fermat
        name: "Speed Test 6 Fermat Numbers"
        python: "3.6"
        script: python speed_test.py --fermat 6
      - <<: *speed-test-fermat
        python: "3.6"
      - <<: *speed-test-fermat
        python: "3.7"
      - <<: *speed-test-fermat
        python: "3.8"
      - <<: *speed-test-fermat
        python: "nightly"
