language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
install:
 - pip install coverage
script:
 - python test.py
 - coverage run test.py && coverage report -m --fail-under=100 --rcfile=coveragerc
 - python speed_test.py --short
 - python speed_test.py --medium
 - python speed_test.py --long
 - python speed_test.py --superlong
 - python speed_test.py --stupidlylong
 - python speed_test.py --fermat 6